/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hari' at '30/6/15 6:53 PM' with Gradle 2.4
 *
 * @author Hari, @date 30/6/15 6:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
